version: "2"
services:
  server:
    container_name: easytrage_server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - "3001:3001"
    links:
      - mongo
    volumes:
      - ./server:/usr/src/app
  client:
    container_name: easytrage_client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data: