version: "2"
services:
  app:
    container_name: easytrage
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    links:
      - mongo
    volumes:
      - /usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data:
